name: Feature
description: This PR introduces a new feature
title: "[feature]: "
labels: []
body:
  - type: checkboxes
    id: checked-other-issues
    attributes:
      label: No existing issues.
      description: By submitting this issue, you confirm, that you have checked the existing issues for your problem.
      options:
        - label: There is no existing issue for my problem.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please fill in a detailed description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction instruction
      description: If possible, please describe how we can reproduce this bug as detailed as possible
    validations:
      required: false