version: 'test-{build}'
environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '8'
    - nodejs_version: '10'
platform:
  - x86
  - x64
clone_folder: 'c:\projects\%APPVEYOR_PROJECT_NAME%'
install:
  - ps: 'Install-Product node $env:nodejs_version $env:platform'
  - ps: '$NpmVersion = (npm -v).Substring(0,1)'
  - ps: 'if($NpmVersion -eq 5) { npm install -g npm@5 }'
  - ps: npm --version
  - npm install
  - ps: |-
      Invoke-WebRequest "https://github.com/MSOpenTech/redis/releases/download/win-2.8.17.4/redis-2.8.17.zip" -OutFile .\redis-2.8.17.zip;
      $destFolder = "redis-2.8.17";
      $shell = new-object -com shell.application;

      $zip = $shell.NameSpace("$pwd\redis-2.8.17.zip");
      if (Test-Path $pwd\$destFolder )
      {
          del $pwd\$destFolder -Force -Recurse
      }
      md ".\redis-2.8.17";
      foreach($item in $zip.items())
      {
          $shell.Namespace("$pwd\redis-2.8.17").copyhere($item);
      }
      cd $destFolder
      .\redis-server.exe --service-install
      .\redis-server.exe --service-start
      cd ..
test_script:
  - echo %cd%
  - node --version
  - npm --version
  - ps: Start-Sleep -s 15
  - npm test
build: 'off'
