name: Bug Report
description: Report a problem with the js-controller
title: "[bug]: "
labels: ["bug :lady_beetle:"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!

  - type: checkboxes
    id: checked-other-issues
    attributes:
      label: No existing issues.
      description: By submitting this issue, you confirm, that you have checked the existing issues for your problem.
      options:
        - label: There is no existing issue for my problem.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please fill in a detailed description of the bug
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction instruction
      description: If possible, please describe how we can reproduce this bug as detailed as possible
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: JS-controller version
      description: Please fill in the version of js-controller
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node version
      description: Please fill in the version of Node.js installed, use node -v to show
    validations:
      required: true
