name: 'Install Redis Linux'
description: 'Install Redis and Redis Sentinel on Linux'
author: 'foxriver76'

runs:
  using: 'composite'
  steps:
    - name: Install Redis and Redis Sentinel
      shell: bash
      run: |
        curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
        sudo apt-get update -q
        sudo apt-get install -y redis-server redis-sentinel